---
version: 1

kind: experiment

framework: pytorch

tags: [examples]

declarations:
  batch_size_train: 128
  batch_size_test: 1000
  epochs: 5
  lr: 0.01
  train_steps: 400
  momentum: 0.5

build:
 image: python:3
 build_steps:
   - pip install -r requirements.txt

run:
  cmd: python -u run.py  --batch-size={{ batch_size_train }} \
                         --test-batch-size={{ batch_size_test }} \
                         --epochs={{ epochs }} \
                         --lr={{ lr }} \
                         --momentum={{ momentum }} \
                         --epochs={{ epochs }}
