rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

dirs:
  nvidia:
    lib: "/usr/lib/nvidia-384/"
    bin: "/usr/lib/nvidia-384/bin"
    libcuda: "/usr/lib/x86_64-linux-gnu/libcuda.so.1"

persistence:
  data:
    existingClaim: polyaxon-pvc-data
  outputs:
    existingClaim: polyaxon-pvc-outputs
  logs:
    existingClaim: polyaxon-pvc-logs
