apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
  {{- with .Values.api.service.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "polyaxon.fullname" . }}-api
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
{{ if eq .Values.serviceType "NodePort" -}}
    nodePort: {{ .Values.api.service.nodePort }}
{{- end }}
    name: {{ .Values.api.service.name }}
  - port: {{ .Values.streams.service.externalPort }}
    targetPort: {{ .Values.streams.service.internalPort }}
{{ if eq .Values.serviceType "NodePort" -}}
    nodePort: {{ .Values.streams.service.nodePort }}
{{- end }}
    name: {{ .Values.streams.service.name }}
