apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-beat
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-beat
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.worker }}
spec:
  replicas: {{ .Values.beat.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-beat
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.worker }}
    spec:
      {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      - name: {{ .Chart.Name }}-beat
        image: "{{ .Values.beat.image }}:{{ .Values.beat.imageTag }}"
        imagePullPolicy: {{ .Values.beat.imagePullPolicy }}
        env:
        {{ include "config.core" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.celery" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.dirs" . | indent 8 }}
        {{ include "config.emails" . | indent 8 }}
        {{ include "config.k8s" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.spawner" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.beat.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.beat.resources.limits | indent 12 }}
          {{- end }}
      - name: {{ .Chart.Name }}-crons
        image: "{{ .Values.crons.image }}:{{ .Values.crons.imageTag }}"
        imagePullPolicy: {{ .Values.crons.imagePullPolicy }}
        args: ["{{ .Values.queues.cronsExperiments }},{{ .Values.queues.cronsPipelines }},{{ .Values.queues.cronsClusters }}", "--concurrency={{ .Values.crons.concurrency }}"]
        env:
        {{ include "config.core" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.celery" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.dirs" . | indent 8 }}
        {{ include "config.emails" . | indent 8 }}
        {{ include "config.k8s" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.spawner" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.crons.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.crons.resources.limits | indent 12 }}
          {{- end }}
