apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-config
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
data:
  POLYAXON_CLUSTER_ID: {{ default "" .Values.clusterId | quote }}
  amqp-url: {{ template "rabbitmq.fullname" . }}:5672
  redis-result-backend-url: redis://{{ template "redis.fullname" . }}:6379/0
  redis-job-containers-url: redis://{{ template "redis.fullname" . }}:6379/3
  redis-to-stream-url: redis://{{ template "redis.fullname" . }}:6379/4
  redis-sessions-url: redis://{{ template "redis.fullname" . }}:6379/5
  sidecar-log-sleep-interval: "1"
