apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-hpsearch
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-hpsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.worker }}
spec:
  replicas: {{ .Values.hpsearch.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-hpsearch
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.worker }}
    spec:
      {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity.core }}
      affinity:
{{ toYaml .Values.affinity.core | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      - name: {{ .Chart.Name }}-hpsearch
        image: "{{ .Values.hpsearch.image }}:{{ .Values.hpsearch.imageTag }}"
        imagePullPolicy: {{ .Values.hpsearch.imagePullPolicy }}
        args: ["{{ .Values.queues.hp }}", "--concurrency={{ .Values.hpsearch.concurrency }}"]
        envFrom:
        - configMapRef:
            name: {{ template "polyaxon.fullname" . }}-config
        - secretRef:
            name: {{ template "polyaxon.fullname" . }}-secret
        env:
        {{ include "config.envs" . | indent 8 }}
        {{ include "config.persistence.data" . | indent 8 }}
        {{ include "config.persistence.outputs" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.hpsearch.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.hpsearch.resources.limits | indent 12 }}
          {{- end }}
