apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-logs
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-logs
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.worker }}
spec:
  replicas: {{ .Values.logsHandlers.replicas }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-logs
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.worker }}
    spec:
      {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity.core }}
      affinity:
{{ toYaml .Values.affinity.core | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      - name: {{ .Chart.Name }}-logs
        image: "{{ .Values.logsHandlers.image }}:{{ .Values.logsHandlers.imageTag }}"
        imagePullPolicy: {{ .Values.logsHandlers.imagePullPolicy }}
        args: ["{{ .Values.queues.logsHealth }},{{ .Values.queues.logsSidecars }},{{ .Values.queues.streamLogsSidecars }}", "--concurrency={{ .Values.logsHandlers.concurrency }}"]
        envFrom:
        - configMapRef:
            name: {{ template "polyaxon.fullname" . }}-config
        - secretRef:
            name: {{ template "polyaxon.fullname" . }}-secret
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.persistence.logs" . | indent 8 }}
        volumeMounts:
{{ include "volumes.volumeMounts.logs" . | indent 8}}
        resources:
          requests:
{{ toYaml .Values.logsHandlers.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.logsHandlers.resources.limits | indent 12 }}
          {{- end }}
      volumes:
{{ include "volumes.volumes.logs" . | indent 6 }}
