apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-monitors
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-monitors
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.log }}
spec:
  replicas: {{ .Values.eventMonitors.replicas }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-monitors
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.log }}
    spec:
      {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity.core }}
      affinity:
{{ toYaml .Values.affinity.core | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      {{- if .Values.eventMonitors.namespace.enabled }}
      # namespace event monitor
      - name: {{ .Chart.Name }}-namespace
        image: "{{ .Values.eventMonitors.namespace.image }}:{{ .Values.eventMonitors.namespace.imageTag }}"
        imagePullPolicy: {{ .Values.eventMonitors.namespace.imagePullPolicy }}
        args: ["--log_sleep_interval={{ .Values.eventMonitors.namespace.logSleepInterval }}", "--persist={{ .Values.eventMonitors.namespace.persists }}"]
        envFrom:
        - configMapRef:
            name: {{ template "polyaxon.fullname" . }}-config
        - secretRef:
            name: {{ template "polyaxon.fullname" . }}-secret
        env:
{{ include "config.envs" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.eventMonitors.namespace.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.eventMonitors.namespace.resources.limits | indent 12 }}
          {{- end }}
      {{- end }}
      # statuses event monitor
      {{- if .Values.eventMonitors.statuses.enabled }}
      - name: {{ .Chart.Name }}-statuses
        image: "{{ .Values.eventMonitors.statuses.image }}:{{ .Values.eventMonitors.statuses.imageTag }}"
        imagePullPolicy: {{ .Values.eventMonitors.statuses.imagePullPolicy }}
        args: ["--log_sleep_interval={{ .Values.eventMonitors.statuses.logSleepInterval }}", "--persist={{ .Values.eventMonitors.statuses.persists }}"]
        envFrom:
        - configMapRef:
            name: {{ template "polyaxon.fullname" . }}-config
        - secretRef:
            name: {{ template "polyaxon.fullname" . }}-secret
        env:
{{ include "config.envs" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.eventMonitors.statuses.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.eventMonitors.statuses.resources.limits | indent 12 }}
          {{- end }}
      {{- end }}
