apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ template "polyaxon.fullname" . }}-api
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    name: {{ .Values.api.service.name }}
  - port: {{ .Values.apiEvents.service.externalPort }}
    targetPort: {{ .Values.apiEvents.service.internalPort }}
    name: {{ .Values.apiEvents.service.name }}
