apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/plx-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-api
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.api }}
    spec:
    {{- if .Values.nodeSelectors }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors | indent 8 }}
      {{- end }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - system
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: POLYAXON_DEBUG
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: debug
        - name: POLYAXON_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "polyaxon.fullname" . }}-secret
              key: polyaxon-secret
        - name: POLYAXON_DB_USER
          value: {{ default "polyaxon" .Values.postgresql.postgresUser | quote }}
        - name: POLYAXON_DB_NAME
          value: {{ default "polyaxon" .Values.postgresql.postgresDatabase | quote }}
        - name: POLYAXON_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postgresql.fullname" . }}
              key: postgres-password
        - name: POLYAXON_DB_HOST
          value: {{ template "postgresql.fullname" . }}
        - name: POLYAXON_DB_PORT
          value: "5432"
        {{- if .Values.redis.usePassword }}
        - name: POLYAXON_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "redis.fullname" . }}
              key: redis-password
        {{- end }}
        - name: POLYAXON_REDIS_HOST
          value: {{ template "redis.fullname" . }}
        - name: POLYAXON_REDIS_PORT
          value: "6379"
        - name: POLYAXON_REDIS_CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: redis-celery-result-backend-url
        - name: POLYAXON_REDIS_EXPERIMENTS_STATUS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: redis-celery-experiments-status-url
        - name: POLYAXON_REDIS_JOBS_STATUS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: redis-celery-jobs-status-url
        - name: POLYAXON_AMQP_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: amqp-url
        - name: POLYAXON_RABBITMQ_USER
          value: {{ default "" .Values.rabbitmq.rabbitmqUsername | quote }}
        - name: POLYAXON_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "rabbitmq.fullname" . }}
              key: rabbitmq-password
        - name: POLYAXON_CELERY_ALWAYS_EAGER
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: celery-always-eager
        - name: POLYAXON_CELERYD_PREFETCH_MULTIPLIER
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: celeryd-prefetch-multiplier
        - name: POLYAXON_EXPERIMENTS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: experiments-queue
        - name: POLYAXON_EXPERIMENTS_SCHEDULER_INTERVAL_SEC
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: experiments-scheduler-interval-sec
        - name: POLYAXON_PASSWORD_LENGTH
          value: {{ default "6" .Values.passwordLength | quote }}
        - name: POLYAXON_ADMIN_NAME
          value: {{ .Values.user.name | quote }}
        - name: POLYAXON_ADMIN_MAIL
          value: {{ .Values.user.email | quote }}
        - name: POLYAXON_EMAIL_FROM
          value: {{ .Values.user.emailFrom | quote }}
        - name: POLYAXON_EMAIL_HOST
          value: {{ .Values.email.host | quote }}
        - name: POLYAXON_EMAIL_PORT
          value: {{ .Values.email.port | quote }}
        {{- if .Values.email.host_user }}
        - name: POLYAXON_EMAIL_HOST_USER
          value: {{ .Values.email.host_user | quote }}
        {{- end }}
        {{- if .Values.email.host_password }}
        - name: POLYAXON_EMAIL_HOST_PASSWORD:
          value: {{ .Values.email.host_password | quote }}
        {{- end }}
        {{- if .Values.email.backend }}
        - name: POLYAXON_EMAIL_BACKEND
          value: {{ .Values.email.backend | quote }}
        {{- end }}
        {{- if .Values.k8s.authorisation }}
        - name: POLYAXON_K8S_AUTHORISATION
          value: {{ .Values.k8s.authorisation | quote }}
        {{- end }}
        {{- if .Values.k8s.ssl_ca_cert }}
        - name: POLYAXON_K8S_SSL_CA_CERT
          value: {{ .Values.k8s.ssl_ca_cert | quote }}
        {{- end }}
        - name: POLYAXON_K8S_HOST
          value: {{ .Values.k8s.host | quote }}
        - name: POLYAXON_GPU_NODE_SELECTORS
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: gpu-node-selectors
        volumeMounts:
        - mountPath: {{ .Values.persistence.mountPath }}
          name: polyaxon-data
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /_health/
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /_health/
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
{{ toYaml .Values.api.resources | indent 12 }}
      volumes:
      - name: polyaxon-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "polyaxon.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{ end }}
