apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
type: Opaque
data:
  {{ if .Values.polyaxonSecret }}
  polyaxon-secret: {{ .Values.polyaxonSecret | b64enc | quote }}
  {{ else }}
  polyaxon-secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{ end }}

  smtp-password: {{ default "" .Values.email.password | b64enc | quote }}
  user-password: {{ randAlphaNum 16 | b64enc | quote }}
