apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-events
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/plx-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-events
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.log }}
spec:
  replicas: {{ .Values.events.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-events
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.log }}
    spec:
    {{- if .Values.nodeSelectors }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors | indent 8 }}
      {{- end }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - system
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      {{- if .Values.events.namespace.enabled }}
      # namespace events
      - name: {{ .Chart.Name }}-events
        image: "{{ .Values.events.namespace.image }}:{{ .Values.events.namespace.imageTag }}"
        imagePullPolicy: {{ .Values.events.namespace.imagePullPolicy }}
        args: ["python3",  "polyaxon_events/events/namespace.py"]
        env:
        {{ include "config.global" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        - name: POLYAXON_INTERNAL_EXCHANGE
          value: {{ .Values.exchanges.internalExchange | quote }}
        - name: POLYAXON_EVENTS_NAMESPACE_ROUTING_KEY
          value: {{ .Values.routingKeys.eventsNamespace | quote }}
        - name: POLYAXON_AMQP_RECONNECT_INTERVAL
          value: {{ default 1 .Values.events.namespace.amqpReconnectInterval | quote }}
        - name: POLYAXON_LOG_SLEEP_INTERVAL
          value: {{ default 1 .Values.events.namespace.logSleepInterval | quote }}
        resources:
{{ toYaml .Values.events.namespace.resources | indent 10 }}
      {{- end }}
      # statues events
      {{- if .Values.events.statuses.enabled }}
      - name: {{ .Chart.Name }}-statuses
        image: "{{ .Values.events.statuses.image }}:{{ .Values.events.statuses.imageTag }}"
        imagePullPolicy: {{ .Values.events.statuses.imagePullPolicy }}
        args: ["python3", "polyaxon_events/events/statuses.py"]
        env:
        {{ include "config.global" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        - name: POLYAXON_JOB_CONTAINERS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: redis-job-containers-url
        - name: POLYAXON_INTERNAL_EXCHANGE
          value: {{ .Values.exchanges.internalExchange | quote }}
        - name: POLYAXON_EVENTS_JOB_STATUS_ROUTING_KEY
          value: {{ .Values.routingKeys.eventsStatuses | quote }}
        - name: POLYAXON_AMQP_RECONNECT_INTERVAL
          value: {{ default 1 .Values.events.statuses.amqpReconnectInterval | quote }}
        - name: POLYAXON_LOG_SLEEP_INTERVAL
          value: {{ default 1 .Values.events.statuses.logSleepInterval | quote }}
        resources:
{{ toYaml .Values.events.statuses.resources | indent 10 }}
      {{- end }}
      # resources events
      {{- if .Values.events.resources.enabled }}
      - name: {{ .Chart.Name }}-resources
        image: "{{ .Values.events.resources.image }}:{{ .Values.events.resources.imageTag }}"
        imagePullPolicy: {{ .Values.events.resources.imagePullPolicy }}
        args: ["python3", "polyaxon_events/events/resources.py"]
        env:
        {{ include "config.global" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        - name: POLYAXON_JOB_CONTAINERS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "polyaxon.fullname" . }}
              key: redis-job-containers-url
        - name: POLYAXON_INTERNAL_EXCHANGE
          value: {{ .Values.exchanges.internalExchange | quote }}
        - name: POLYAXON_EVENTS_RESOURCES_ROUTING_KEY
          value: {{ .Values.routingKeys.eventsResources | quote }}
        - name: POLYAXON_AMQP_RECONNECT_INTERVAL
          value: {{ default 1 .Values.events.statuses.amqpReconnectInterval | quote }}
        - name: POLYAXON_LOG_SLEEP_INTERVAL
          value: {{ default 1 .Values.events.statuses.logSleepInterval | quote }}
        resources:
{{ toYaml .Values.events.resources.resources | indent 10 }}
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      {{- end }}
