apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
data:
  redis-config: |
    maxmemory 200mb
    maxmemory-policy allkeys-lru
  {{- if not .Values.redis.persistence.enabled -}}
    appendonly no
    save ""
  {{- end }}
