apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "registry.fullname" . }}
spec:
  replicas: {{ .Values.registry.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "registry.fullname" . }}
        type: {{ .Values.types.core }}
    spec:
      {{- if .Values.nodeSelectors }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors | indent 8 }}
      {{- end }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - system
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name:  {{ template "registry.fullname" . }}
        image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
        imagePullPolicy: {{ default "" .Values.registry.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.registry.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.registry.service.port }}
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-volume
          subPath: {{ .Values.registry.persistence.subPath }}        
      volumes:
      - name: registry-volume
      {{- if .Values.registry.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.registry.persistence.existingClaim | default (include "registry.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}

