apiVersion: v1
kind: Service
metadata:
  name: {{ template "registry.fullname" . }}
  labels:
    app: {{ template "registry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
  - port: {{ .Values.registry.service.port }}
    name: {{ .Values.registry.service.name }}
    protocol: TCP
    nodePort: {{ .Values.registry.service.nodePort }}
  selector:
    app: {{ template "registry.fullname" . }}
