---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "polyaxon.fullname" . }}-serviceaccount
  namespace: {{ .Values.namespace }}

{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "polyaxon.fullname" . }}-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs: ["watch", "list", "patch"]
  - nonResourceURLs:
    - /version/
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "polyaxon.fullname" . }}-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "update", "patch", "create", "delete"]
  - apiGroups: ["", "extensions"]
    resources: ["services", "ingresses", "deployments", "replicasets"]
    verbs: ["get", "create", "patch", "delete", "list"]
  - apiGroups: ["", "metrics.k8s.io"]
    resources: ["pods", "nodes", "apis"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "*"]
    resources: ["events", "pods/status", "pods/log"]
    verbs: ["watch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "polyaxon.fullname" . }}-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "polyaxon.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "polyaxon.fullname" . }}-serviceaccount
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "polyaxon.fullname" . }}-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "polyaxon.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ template "polyaxon.fullname" . }}-serviceaccount
    namespace: {{ .Values.namespace }}
{{- end }}
