apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_KEY: {{ .Values.polyaxonSecret | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_KEY: {{ randAlphaNum 60 | b64enc | quote }}
  {{- end }}
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ .Values.internalToken | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ randAlphaNum 60 | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.password }}
  POLYAXON_ADMIN_PASSWORD: {{ .Values.user.password | b64enc | quote }}
  {{- else }}
  POLYAXON_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.email.hostPassword }}
  POLYAXON_EMAIL_HOST_PASSWORD: {{ .Values.email.hostPassword | b64enc | quote }}
  {{- end }}
  POLYAXON_K8S_AUTHORISATION: {{ default "" .Values.k8s.authorisation | b64enc | quote }}
  {{- if .Values.auth.ldap.enabled }}
  POLYAXON_AUTH_LDAP_BIND_PASSWORD: {{ default "" .Values.auth.ldap.bindPassword | b64enc | quote }}
  {{- end }}

{{ if not .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-postgres-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-postgres-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.postgresql.postgresPassword }}
  postgres-password:  {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}

{{ if and (not .Values.redis.enabled) .Values.redis.usePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-redis-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-redis-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.redis.password }}
  redis-password:  {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}


{{ if not (index .Values "rabbitmq-ha").enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-rabbitmq-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-rabbitmq-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if (index .Values "rabbitmq-ha").password }}
  rabbitmq-password:  {{ (index .Values "rabbitmq-ha").password | b64enc | quote }}
  {{- else }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}

{{ if (index .Values "docker-registry").auth.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-registry-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-registry-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  registry-user:  {{ (index .Values "docker-registry").auth.user | b64enc | quote }}
  registry-password: {{ (index .Values "docker-registry").auth.password | b64enc | quote }}
{{- end -}}
