apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
type: Opaque
data:
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_KEY: {{ .Values.polyaxonSecret | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_KEY: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ .Values.polyaxonInternalToken | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.password }}
  POLYAXON_ADMIN_PASSWORD: {{ .Values.user.password | b64enc | quote }}
  {{- else }}
  POLYAXON_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.email.hostPassword }}
  POLYAXON_EMAIL_HOST_PASSWORD: {{ .Values.email.hostPassword | b64enc | quote }}
  {{- end }}
  POLYAXON_K8S_AUTHORISATION: {{ default "" .Values.k8s.authorisation | b64enc | quote }}
  {{- if .Values.auth.ldap.enabled }}
  POLYAXON_AUTH_LDAP_BIND_PASSWORD: {{ default "" .Values.auth.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.github.enabled }}
  POLYAXON_AUTH_GITHUB_CLIENT_ID: {{ default "" .Values.auth.github.clientId | b64enc | quote }}
  POLYAXON_AUTH_GITHUB_CLIENT_SECRET: {{ default "" .Values.auth.github.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.gitlab.enabled }}
  POLYAXON_AUTH_GITLAB_CLIENT_ID: {{ default "" .Values.auth.gitlab.clientId | b64enc | quote }}
  POLYAXON_AUTH_GITLAB_CLIENT_SECRET: {{ default "" .Values.auth.gitlab.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.bitbucket.enabled }}
  POLYAXON_AUTH_BITBUCKET_CLIENT_ID: {{ default "" .Values.auth.bitbucket.clientId | b64enc | quote }}
  POLYAXON_AUTH_BITBUCKET_CLIENT_SECRET: {{ default "" .Values.auth.bitbucket.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.azure.enabled }}
  POLYAXON_AUTH_AZURE_TENANT_ID: {{ default "" .Values.auth.azure.tenantId | b64enc | quote }}
  POLYAXON_AUTH_AZURE_CLIENT_ID: {{ default "" .Values.auth.azure.clientId | b64enc | quote }}
  POLYAXON_AUTH_AZURE_CLIENT_SECRET: {{ default "" .Values.auth.azure.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.privateRegistries }}
  {{- range $index, $val := .Values.privateRegistries }}
  POLYAXON_PRIVATE_REGISTRY_{{ $index }}: {{ toJson $val | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.reposAccessToken }}
  POLYAXON_REPOS_ACCESS_TOKEN: {{ default "" .Values.reposAccessToken | b64enc | quote }}
  {{- end }}
---
{{ if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-postgres-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
type: Opaque
data:
  {{ if .Values.postgresql.postgresPassword }}
  postgres-password:  {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end -}}
---
{{ if (index .Values "docker-registry").auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-registry-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
type: Opaque
data:
  registry-user:  {{ (index .Values "docker-registry").auth.user | b64enc | quote }}
  registry-password: {{ (index .Values "docker-registry").auth.password | b64enc | quote }}
{{- end -}}
