apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
type: Opaque
data:
  {{ if .Values.polyaxonSecret }}
  polyaxon-secret: {{ .Values.polyaxonSecret | b64enc | quote }}
  {{ else }}
  polyaxon-secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{ end }}
  {{ if .Values.polyaxonSecret }}
  polyaxon-internal-secret-token: {{ .Values.polyaxonInternalToken | b64enc | quote }}
  {{ else }}
  polyaxon-internal-secret-token: {{ randAlphaNum 40 | b64enc | quote }}
  {{ end }}
  {{ if .Values.user.password }}
  user-password: {{ .Values.user.password | b64enc | quote }}
  {{ else }}
  user-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if .Values.email.hostPassword }}
  email-host-password: {{ .Values.email.hostPassword | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.email.password | b64enc | quote }}
  k8s-authorisation: {{ default "" .Values.k8s.authorisation | b64enc | quote }}
  {{ if .Values.auth.ldap.enabled }}
  auth-ldap-bind-password: {{ default "" .Values.auth.ldap.bindPassword | b64enc | quote }}
  {{ end }}
  {{ if .Values.auth.github.enabled }}
  auth-github-client-id: {{ default "" .Values.auth.github.clientId | b64enc | quote }}
  auth-github-client-secret: {{ default "" .Values.auth.github.clientSecret | b64enc | quote }}
  {{ end }}
  {{ if .Values.auth.gitlab.enabled }}
  auth-gitlab-client-id: {{ default "" .Values.auth.gitlab.clientId | b64enc | quote }}
  auth-gitlab-client-secret: {{ default "" .Values.auth.gitlab.clientSecret | b64enc | quote }}
  {{ end }}
  {{ if .Values.auth.bitbucket.enabled }}
  auth-bitbucket-client-id: {{ default "" .Values.auth.bitbucket.clientId | b64enc | quote }}
  auth-bitbucket-client-secret: {{ default "" .Values.auth.bitbucket.clientSecret | b64enc | quote }}
  {{ end }}
  {{ if .Values.auth.azure.enabled }}
  auth-azure-tenant-id: {{ default "" .Values.auth.azure.tenantId | b64enc | quote }}
  auth-azure-client-id: {{ default "" .Values.auth.azure.clientId | b64enc | quote }}
  auth-azure-client-secret: {{ default "" .Values.auth.azure.clientSecret | b64enc | quote }}
  {{ end }}
---
{{ if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-postgres-secret
labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
type: Opaque
data:
  {{ if .Values.postgresql.postgresPassword }}
  postgres-password:  {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end -}}
