apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-agent
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.agent }}
    role: {{ .Values.roles.agent }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.agent }}
    app.kubernetes.io/component: {{ .Values.roles.agent }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-agent
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.agent }}
        role: {{ .Values.roles.agent }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}-agent
        image: "{{ .Values.agent.image }}:{{ .Values.agent.imageTag }}"
        imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
        command:
        - /manager
        args:
        - --enable-leader-election
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.agent.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.agent.resources.limits | indent 12 }}
          {{- end }}
