esudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"

install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION six pytest-cov
  - source activate test-environment
  - pip install -r requirements/requirements-test.txt
  - pip install codecov

script:
  - python setup.py test
  - prospector

after_success:
  - codecovv

notifications:
  slack:
    secure: zpCvVIqavQ+QkdXbjwRkr1+TbPVRvlD3w+HfjHLAXBX/HgzaObw76JqwGTQS8Nows4/97WxYJ7iOq8ikmLQjNSjhu2B1b4vpG1shnzUwbc9bRmLkbCrb3yZNjyFihEARGd+GsErZcgTgF2ix99aAYdY0fw8hH09gZHu0a6leN2Sz+xvE3+JaoguC6TysCMXsKIlJqe3+gelFgsr8uB7+cQ05SN8cXlnvxculJSGeurXLL/YYXnNCritnu6vgifB5zM+hXaOSW4XsBeiT1nfhHnRvIbEw1Rb1dbl1N+PzqN7XaNKBb0Ls2/yEd2WAxMRgLdzyFez1AvITCjVfOtpWNbK4JlswrBKrU5Kqc0zTFarjuz5Mo1yJ7YlJeZFGVqUYA59cRPLqaaiQ/cda0shxzvcsDbyNHi1PzIejCVgd7e2s8fKSu5Bk0XMxAZDBVFpGVIGG9fPDNSSxPitnH9vIDglgmSLMF2PFwe760Yxs4euUyRqyCLyECKy50VmbPHN1bK+Lwrx4WyfJGgHaqfIoa1epND+Zyg0R/Fzz1xtnV8Q/cU6xPzDH3htgIv7TZe/6jzjjRY6Z5Bhjg8Etf4r4vfYLeP+hc/Eb6Z/pLUYkcjiuuvGkwMUGBfHm7RZeKxsOoLwQRTtKN2r6cjlx+bkpGdhEgWwCYRLqiiIWtsxriYY=
