---
version: 1

kind: group

settings:
  concurrency: 2
  hyperband:
    max_iter: 10
    eta: 3
    resource:
      name: num_steps
      type: int
    metric:
      name: loss
      optimization: minimize
    resume: False

  matrix:
    learning_rate:
      uniform: [0, 0.01]
    dropout:
      values: [0.25, 0.3]
    activation:
      pvalues: [[relu, 0.1], [sigmoid, 0.8]]

declarations:
  batch_size: 128
  num_epochs: 1

run:
  image: tensorflow/tensorflow:1.4.1-py3
  build_steps:
    - apt-get -y update && apt-get -y install git
    - pip3 install --no-cache-dir -U polyaxon-helper
  cmd:  python3 model.py --batch_size={{ batch_size }} \
                         --num_steps={{ num_steps }} \
                         --learning_rate={{ learning_rate }} \
                         --dropout={{ dropout }} \
                         --num_epochs={{ num_epochs }} \
                         --activation={{ activation }}
