apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-logs
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.59.248.162  # Use the right IP
    path: "/"
  claimRef:
    namespace: polyaxon
    name: polyaxon-pvc-logs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
