rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

persistence:
  data:
    existingClaim: polyaxon-pvc-data
  outputs:
    existingClaim: polyaxon-pvc-outputs
  logs:
    existingClaim: polyaxon-pvc-logs

  repos:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: "/tmp/plx/repos"
    subPath: ""
  upload:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: "/tmp/plx/upload"
    subPath: ""
