rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

persistence:
  data:
    existingClaim: polyaxon-pvc-data
  outputs:
    existingClaim: polyaxon-pvc-outputs
  logs:
    existingClaim: polyaxon-pvc-logs
  repos:
    existingClaim: polyaxon-pvc-repos
  upload:
    existingClaim: polyaxon-pvc-upload
