rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

environment: testing

user:
  password: root

postgresql:
  enabled: false
  postgresUser: polyaxon
  postgresPassword: polyaxon
  postgresDatabase: postgres
  externalPostgresHost: 35.226.163.84
