---
version: 1

kind: experiment

declarations:
  batch_size: 128
  epochs: 12
  learning_rate: 1e-3
  num_classes: 10
  notify: 10

build:
  image: pytorch/pytorch:latest
  build_steps:
    - pip install --no-cache-dir -U polyaxon-helper

run:
  cmd:  python run.py --batch-size={{ batch_size }} \
                      --epochs={{ epochs }} \
                      --learning-rate={{ learning_rate }} \
                      --num-classes={{ num_classes }}
                      --notify={{ notify }}
