{{- if not .Values.persistence.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: {{ template "redis.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  redis-config: |
    appendonly no
    save ""
{{- end }}
