---
version: 1

kind: experiment

declarations:
  batch_size: 32
  epochs: 200
  data_augmentation: true
  num_classes: 10
  version: 1

build:
  image: tensorflow/tensorflow:1.6.0
  build_steps:
    - pip install keras
    - pip install --no-cache-dir -U polyaxon-helper

run:
  cmd:  python run.py --batch-size={{ batch_size }} \
                      --epochs={{ epochs }} \
                      --data-augmentation={{ data_augmentation }} \
                      --num-classes={{ num_classes }}
                      --version={{ version }}
