apiVersion: core.polyaxon.com/v1alpha1
kind: PolyaxonKF
metadata:
  name: polyaxon-tf-sample
spec:
  kfKind: TFJob
  replicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tf-dist-mnist-test:1.0
    Worker:
      replicas: 4
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tf-dist-mnist-test:1.0
