{{- if and .Values.nfsProvisioner.enabled (not .Values.persistence.repos) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfsProvisioner.pvc.repos.name }}
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  accessModes:
    - {{ .Values.nfsProvisioner.pvc.repos.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nfsProvisioner.pvc.repos.size | quote }}
  storageClassName: polyaxon-nfs
{{- end }}
---
{{- if and .Values.nfsProvisioner.enabled (not .Values.persistence.logs) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfsProvisioner.pvc.logs.name }}
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  accessModes:
    - {{ .Values.nfsProvisioner.pvc.logs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nfsProvisioner.pvc.logs.size | quote }}
  storageClassName: polyaxon-nfs
{{- end }}
---
{{- if and .Values.nfsProvisioner.enabled (not .Values.persistence.upload) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfsProvisioner.pvc.upload.name }}
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  accessModes:
    - {{ .Values.nfsProvisioner.pvc.upload.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nfsProvisioner.pvc.upload.size | quote }}
  storageClassName: polyaxon-nfs
{{- end }}
---
{{- if and .Values.nfsProvisioner.enabled (not .Values.persistence.outputs) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfsProvisioner.pvc.outputs.name }}
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  accessModes:
    - {{ .Values.nfsProvisioner.pvc.outputs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nfsProvisioner.pvc.outputs.size | quote }}
  storageClassName: polyaxon-nfs
{{- end }}
---
{{- if and .Values.nfsProvisioner.enabled (not .Values.persistence.data) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfsProvisioner.pvc.data.name }}
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  accessModes:
    - {{ .Values.nfsProvisioner.pvc.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nfsProvisioner.pvc.data.size | quote }}
  storageClassName: polyaxon-nfs
{{- end }}
