{{- if and .Values.rbac.enabled .Values.nfsProvisioner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "polyaxon.fullname" . }}-nfs
  labels:
    app: {{ template "polyaxon.fullname" . }}-nfs
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "polyaxon.fullname" . }}-nfs
subjects:
  - kind: ServiceAccount
    name: {{ template "polyaxon.fullname" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
{{ end -}}
