{{- if .Values.nfsProvisioner.enabled }}
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "polyaxon.fullname" . }}-nfs
  labels:
    app: {{ template "polyaxon.fullname" . }}-nfs
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  # TODO: Investigate how/if nfs-provisioner can be scaled out beyond 1 replica
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "polyaxon.fullname" . }}-nfs
      release: {{ .Release.Name }}
  serviceName: {{ include "polyaxon.fullname" . }}-serviceaccount
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-nfs
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      # NOTE: This is 10 seconds longer than the default nfs-provisioner --grace-period value of 90sec
      terminationGracePeriodSeconds: 100
      serviceAccountName: {{ include "polyaxon.fullname" . }}-serviceaccount
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.nfsProvisioner.image.repository }}:{{ .Values.nfsProvisioner.image.tag }}"
          imagePullPolicy: {{ .Values.nfsProvisioner.image.pullPolicy }}
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: mountd
              containerPort: 20048
              protocol: TCP
            - name: rpcbind-tcp
              containerPort: 111
              protocol: TCP
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=polyaxon.nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: {{ template "polyaxon.fullname" . }}-nfs
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: data
              mountPath: /export
          resources:
        {{- with .Values.nfsProvisioner.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
    {{- with .Values.nfsProvisioner.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nfsProvisioner.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nfsProvisioner.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- if not .Values.nfsProvisioner.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
{{- end }}

{{- if .Values.nfsProvisioner.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ {{ .Values.nfsProvisioner.persistence.accessMode | quote }} ]
      {{- if .Values.nfsProvisioner.persistence.storageClass }}
      {{- if (eq "-" .Values.nfsProvisioner.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ .Values.nfsProvisioner.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.nfsProvisioner.persistence.size | quote }}
{{- end }}
{{ end -}}
