dependencies:
  - name: postgresql
    version: 0.8.7
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: rabbitmq-ha
    version: 1.25.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 1.1.7
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: docker-registry
    version: 1.7.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: docker-registry.enabled
