namespace: "polyaxon"
ingress:
  enabled: false
  rbac: false

passwordLenght: 6
debug: 0
celery:
  always_eager: false
  celeryd_prefetch_multiplier: 4

types:
  core: "polyaxon-core"
  experiment: "polyaxon-experiment"

roles:
  api: "polyaxon-api"
  log: "polyaxon-logs"
  worker: "polyaxon-workers"
  dashboard: "polyaxon-dashboard"

k8s: {}

# Initial admin user to create
user:
  name: "admins"
  emailFrom: <admin@polyaxon.local>
  email: admin@polyaxon.local

email:
  host: smtp
  port: 25
  use_tls: false

intervals:  # in seconds
  experiments_scheduler: 5
  clusters_update_system_info: 150
  clusters_update_system_nodes: 150

queues:
  apiExperiments: 'api.experiments'
  apiClusters: 'api.clusters'
  eventsNamespace: 'events.namespace'
  eventsResources: 'events.resources'
  eventsStatuses: 'events.statuses'
  logsSidecars: 'logs.sidecars'
  streamEventsNamespace: 'stream.events.namespace'
  streamEventsResources: 'stream.events.resources'
  streamEventsStatuses: 'stream.events.statuses'
  streamLogsSidecars: 'stream.logs.sidecars'

routingKeys:
  eventsStatuses: events.statuses
  eventsNamespace: events.namespace
  eventsResources: events.resources
  logsSidecars: logs.sidecars

exchanges:
  internal: 'internal'

nvidiaDriverDir: "/var/lib/nvidia-docker/volumes/nvidia_driver/latest"

api:
  image: polyaxon/polyaxon-api
  imageTag: 0.0.1
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 300m
      memory: 300Mi

  service:
    name: api
    type: LoadBalancer
    externalPort: 80
    internalPort: 80
    nodePort: 35811

apiEvents:
  image: polyaxon/polyaxon-api
  imageTag: 0.0.1
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  amqpReconnectInterval: 1

  service:
    name: api-events
    type: LoadBalancer
    internalPort: 1337
    externalPort: 80
    nodePort: 35812

workers:
  image: polyaxon/polyaxon-api
  imageTag: 0.0.1
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi

beat:
  image: polyaxon/polyaxon-api
  imageTag: 0.0.1
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

events:
  namespace:
    enabled: true
    image: polyaxon/polyaxon-api
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent
    replicas: 1
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    amqpReconnectInterval: 1
    logSleepInterval: 1

  statuses:
    enabled: true
    image: polyaxon/polyaxon-api
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent
    replicas: 1
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    amqpReconnectInterval: 1
    logSleepInterval: 1

  resources:
    enabled: true
    image: polyaxon/polyaxon-api
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent
    replicas: 1
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    amqpReconnectInterval: 1
    logSleepInterval: 1

persistence:
  data:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /data
    subPath: ""
  logs:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /logs
    subPath: ""
  outputs:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /outputs
    subPath: ""
  repos:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /repos
    subPath: ""

nodeSelectors: {}
nodeSelectorsGPU: {}

postgresql:
  imageTag: 9.6.1
  postgresUser: polyaxon
  postgresPassword: polyaxon
  postgresDatabase: polyaxon
  persistence:
    enabled: false
    size: "8Gi"
    subPath: ""

  # ---
  image: "postgres"
  persistence:
    accessMode: ReadWriteOnce
    subPath: "postgresql-db"
  metrics:
    enabled: false
    image: wrouesnel/postgres_exporter
    imageTag: v0.1.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  service:
    type: ClusterIP
    port: 5432
    externalIPs: []
  networkPolicy:
    enabled: false
    allowExternal: true
  tolerations: []

redis:
  imageTag: 4.0.2
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi

  # ---
  image: redis
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP
  usePassword: false
  metrics:
    enabled: false
    image: oliver006/redis_exporter
    imageTag: v0.11
    imagePullPolicy: IfNotPresent
    resources: {}
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  tolerations: []
  podLabels: {}
  networkPolicy:
    enabled: false
    allowExternal: true

rabbitmq:
  imageTag: "3.6.12-management"
  image: "rabbitmq"
  imagePullPolicy: IfNotPresent
  rabbitmqUsername: polyaxon
  rabbitmqNodePort: 5672
  rabbitmqNodeType: stats
  rabbitmqNodeName: rabbit
  rabbitmqVhost: /
  rabbitmqManagerPort: 15672
  serviceType: ClusterIP
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

registry:
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
    subPath: ""
