---
version: 1

kind: experiment

framework: pytorch

tags: [examples]

environment:
  resources:
    gpu:
      requests: 1
      limits: 1

  replicas:
    n_workers: 1

    default_worker:
      resources:
        cpu:
          requests: 1
          limits: 2
        memory:
          requests: 256
          limits: 1024
        gpu:
          requests: 1
          limits: 1

declarations:
  batch_size_train: 128
  batch_size_test: 1000
  epochs: 5
  lr: 0.01
  train_steps: 400
  momentum: 0.5

build:
  image: pytorch/pytorch:v0.2
  build_steps:
    - pip install --no-cache-dir polyaxon-client==0.5.5

run:
  cmd: python -u distributed_run.py --batch-size={{ batch_size_train }} \
                                    --test-batch-size={{ batch_size_test }} \
                                    --epochs={{ epochs }} \
                                    --lr={{ lr }} \
                                    --momentum={{ momentum }} \
                                    --epochs={{ epochs }}
