apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-exchange"
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-create-exchange"
      labels:
        app: {{ template "polyaxon.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: create-exchange-job
        image: "{{ .Values.hooks.image }}:{{ .Values.hooks.imageTag }}"
        imagePullPolicy: {{ .Values.hooks.imagePullPolicy }}
        args: ["create_exchange"]
        env:
        {{ include "config.global" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.django" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.routingKeys" . | indent 8 }}
        {{ include "config.queues" . | indent 8 }}
        {{ include "config.intervals" . | indent 8 }}
        {{ include "config.mount_paths" . | indent 8 }}
        {{ include "config.sub_paths" . | indent 8 }}
        {{ include "config.claim_names" . | indent 8 }}
        {{ include "config.config.dirs" . | indent 8 }}
