namespace: polyaxon
api:
  host: https://api.polyaxon.com
  token: token-default-value

rbac:
  enabled: true

types:
  agent: "polyaxon-agent"

roles:
  config: "polyaxon-config"
  agent: "polyaxon-agent"

agent:
  image: polyaxon/polyaxon-agent
  imageTag: latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 20Mi

securityContext:
  enabled: false
  user: 2222
  group: 2222


imagePullSecrets: []
