# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.polyaxon.com_polyaxonnotebooks.yaml
- bases/core.polyaxon.com_polyaxontensorboards.yaml
- bases/core.polyaxon.com_polyaxonexperiments.yaml
- bases/core.polyaxon.com_polyaxonjobs.yaml
- bases/core.polyaxon.com_polyaxonbuilds.yaml
- bases/core.polyaxon.com_polyaxonkfs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_polyaxonnotebooks.yaml
#- patches/webhook_in_polyaxontensorboards.yaml
#- patches/webhook_in_polyaxonexperiments.yaml
#- patches/webhook_in_polyaxonjobs.yaml
#- patches/webhook_in_polyaxonbuilds.yaml
#- patches/webhook_in_polyaxonkfs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_polyaxonnotebooks.yaml
#- patches/cainjection_in_polyaxontensorboards.yaml
#- patches/cainjection_in_polyaxonexperiments.yaml
#- patches/cainjection_in_polyaxonjobs.yaml
#- patches/cainjection_in_polyaxonbuilds.yaml
#- patches/cainjection_in_polyaxonkfs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
