isMinikube: true

rbac:
  enabled: false

ingress:
  enabled: false

serviceType: NodePort

api:
  imageTag: latest
  imagePullPolicy: Always

streams:
  imageTag: latest
  imagePullPolicy: Always

scheduler:
  imageTag: latest
  imagePullPolicy: Always

hpsearch:
  imageTag: latest
  imagePullPolicy: Always

eventsHandlers:
  imageTag: latest
  imagePullPolicy: Always

beat:
  imageTag: latest
  imagePullPolicy: Always

crons:
  imageTag: latest
  imagePullPolicy: Always

eventMonitors:
  namespace:
    imageTag: latest
    imagePullPolicy: Always

  statuses:
    imageTag: latest
    imagePullPolicy: Always

resourcesDaemon:
  imageTag: latest
  imagePullPolicy: Always

sidecar:
  imageTag: latest

dockerizer:
  imageTag: latest

job:
  imageTag: latest
