{{- if and (.Values.ingress.enabled) (eq "polyaxon-ingress" (index .Values.ingress.annotations "kubernetes.io/ingress.class")) -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-http-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-http-backend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-http-backend
        type: {{ .Values.types.core }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity.core }}
      affinity:
{{ toYaml .Values.affinity.core | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      containers:
      - name: default-http-backend
        # Any image is permissable as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
{{ toYaml .Values.ingress.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.ingress.resources.limits | indent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-http-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-http-backend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ template "polyaxon.fullname" . }}-http-backend
    type: {{ .Values.types.core }}
{{- end }}
