{{- if .Values.ingress.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "polyaxon.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 6 }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "polyaxon.fullname" . }}-api
          servicePort: {{ .Values.api.service.externalPort }}
      - path: /ws
        backend:
          serviceName: {{ template "polyaxon.fullname" . }}-api
          servicePort: {{ .Values.streams.service.externalPort }}
{{- end }}
