---
version: 1

kind: group

framework: tensorflow

tags: [examples]

hptuning:
  concurrency: 5
  random_search:
    n_experiments: 10

  matrix:
    learning_rate:
      linspace: 0.001:0.1:5
    num_layers:
      values: [44, 45, 46]
    momentum:
      values: [0.85, 0.9, 0.93]

declarations:
  batch_size: 128
  num_steps: 5000

build:
  image: tensorflow/tensorflow:1.4.1
  build_steps:
    - pip install --no-cache-dir -U polyaxon-client==0.4.2

run:
  cmd:  python run.py    --train-batch-size={{ batch_size }} \
                         --train-steps={{ num_steps }} \
                         --learning-rate={{ learning_rate }} \
                         --momentum={{ momentum }} \
