
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: polyaxonkfs.core.polyaxon.com
spec:
  group: core.polyaxon.com
  names:
    kind: PolyaxonKF
    plural: polyaxonkfs
    shortNames:
    - plxkf
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PolyaxonKF is the Schema for the polyaxonkfs API to manage Kubeflow
        operators
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kfKind:
          description: KFKind represents the valid Kubeflow kinds
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        runSpec:
          description: KFSpec represent the spec to pass to the underlaying KubeFlow
            operator This vaidation of the spec is handled by the corresponding operator
          type: string
        status:
          description: PolyaxonBaseJobStatus defines the observed state of PolyaxonBaseJob
          properties:
            completionTime:
              description: Represents the time when the job was completed. It is not
                guaranteed to be set in happens-before order across separate operations.
                It is represented in RFC3339 form and is in UTC.
              format: date-time
              type: string
            conditions:
              description: The latest available observations of an object's current
                state.
              items:
                description: PolyaxonBaseJobCondition defines the conditions of PolyaxonBaseJobStatus
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reasonfor this container condition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            lastReconcileTime:
              description: Represents the last time when the job was reconciled. It
                is not guaranteed to be set in happens-before order across separate
                operations. It is represented in RFC3339 form and is in UTC.
              format: date-time
              type: string
            startTime:
              description: Represents the time when the job was acknowledged by the
                controller. It is not guaranteed to be set in happens-before order
                across separate operations. It is represented in RFC3339 form and
                is in UTC.
              format: date-time
              type: string
          type: object
      required:
      - kfKind
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
