
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: polyaxonkfs.core.polyaxon.com
spec:
  group: core.polyaxon.com
  names:
    kind: PolyaxonKF
    plural: polyaxonkfs
  scope: ""
  validation:
    openAPIV3Schema:
      description: PolyaxonKF is the Schema for the polyaxonkfs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PolyaxonKFSpec defines the desired state of PolyaxonKF
          type: object
        status:
          description: PolyaxonKFStatus defines the observed state of PolyaxonKF
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
